In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt("/home/soniya/Documents/work/Computer-Vision-with-Python/DATA/bank_note_data.txt",delimiter = ",")

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

Now we are going to separate labels from the actual features.

In [4]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split
# This splits the data in two parts...that is train data and test data 
# and also distributes them randomly.

In [10]:
np.__version__

'1.17.0'

## As the numpy's latest version has removed numpy.testing.nosetester.....so I have downgraded the version of numpy.

In [11]:
# Test_size says that 33% will go to X_test.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [13]:
len(X_train)

919

In [14]:
len(X)

1372

In [15]:
len(X_test)

453

In [16]:
X_test.max()

17.1116

In [17]:
# We scale or standardize the data.
from sklearn.preprocessing import MinMaxScaler
# This is used if the difference between the X_test.max() and X_test.min()
# is large.

In [18]:
scalar_object = MinMaxScaler()

In [19]:
scalar_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [20]:
scaled_X_train = scalar_object.transform(X_train)

In [21]:
scaled_X_test = scalar_object.transform(X_test)

In [22]:
scaled_X_train.max()

1.0000000000000002

In [23]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [24]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [26]:
from keras.models import Sequential
from keras.layers import Dense

In [32]:
model = Sequential()

model.add(Dense(4,input_dim = 4, activation = 'relu'))
# '4' is the number of neurons or features.This basically is the input layer.

model.add(Dense(8,activation = 'relu'))
# This is the hidden layer.

model.add(Dense(1, activation = 'sigmoid'))

In [33]:
# Now we will compile the model.
model.compile(loss = 'binary_crossentropy', optimizer = 'adam',metrics = ['accuracy'])

In [34]:
model.fit(scaled_X_train, y_train, epochs = 50, verbose = 2)
# One epoch is going through the data one time.

Epoch 1/50
 - 2s - loss: 0.6561 - accuracy: 0.5495
Epoch 2/50
 - 0s - loss: 0.6436 - accuracy: 0.5495
Epoch 3/50
 - 0s - loss: 0.6326 - accuracy: 0.5495
Epoch 4/50
 - 0s - loss: 0.6216 - accuracy: 0.5495
Epoch 5/50
 - 0s - loss: 0.6093 - accuracy: 0.5560
Epoch 6/50
 - 0s - loss: 0.5969 - accuracy: 0.6181
Epoch 7/50
 - 0s - loss: 0.5831 - accuracy: 0.6670
Epoch 8/50
 - 0s - loss: 0.5682 - accuracy: 0.7116
Epoch 9/50
 - 0s - loss: 0.5537 - accuracy: 0.7606
Epoch 10/50
 - 0s - loss: 0.5391 - accuracy: 0.7845
Epoch 11/50
 - 0s - loss: 0.5235 - accuracy: 0.7954
Epoch 12/50
 - 0s - loss: 0.5070 - accuracy: 0.8030
Epoch 13/50
 - 0s - loss: 0.4903 - accuracy: 0.8183
Epoch 14/50
 - 0s - loss: 0.4723 - accuracy: 0.8477
Epoch 15/50
 - 0s - loss: 0.4552 - accuracy: 0.8498
Epoch 16/50
 - 0s - loss: 0.4356 - accuracy: 0.8640
Epoch 17/50
 - 0s - loss: 0.4158 - accuracy: 0.8836
Epoch 18/50
 - 0s - loss: 0.3954 - accuracy: 0.8890
Epoch 19/50
 - 0s - loss: 0.3760 - accuracy: 0.9010
Epoch 20/50
 - 0s - l

In [35]:
# Predicting on new data.
model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [37]:
# Now we will evaluate the model.
model.metrics_names

['loss', 'accuracy']

In [38]:
from sklearn.metrics import confusion_matrix,classification_report

In [39]:
predictions = model.predict_classes(scaled_X_test)

In [40]:
confusion_matrix(y_test,predictions)
# This will give us our confusion matrix.

array([[251,   6],
       [ 10, 186]])

In [41]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.96      0.98      0.97       257
         1.0       0.97      0.95      0.96       196

    accuracy                           0.96       453
   macro avg       0.97      0.96      0.96       453
weighted avg       0.96      0.96      0.96       453



In [44]:
# Saving the model
model.save("/home/soniya/Desktop/Models/mymodel1.h5")

In [45]:
# To load the model
from keras.models import load_model

In [47]:
newmodel = load_model("/home/soniya/Desktop/Models/mymodel1.h5")

In [49]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    